name: BE deploy staging 
run-name: BE deploy staging
on:
  push:
    - 'staging' #ấn vào merge cũng là 1 hành động push code lên 
    # yêu cầu merge là pull request 
  paths: 
    - backend/**
defaults:
  run:
    working-directory: ./backend
jobs:
  build:
    runs-on: [self-hosted, backend-server-staging] #label của runner để phân biệt các runner khác nhau 
    steps:
    - name: Checkout # checkout để thực hiện build image 
      uses: actions/checkout@v4.2.2
    - name: Using docker to check convention code 
      run: |  
        ls
        echo "Build image"

