name: BE-CI
run-name: BE-CI
on:
  pull_request: 
    branches:
      - 'develop'
    paths:
        - backend/**
defaults:
  run:
    working-directory: ./backend
jobs:
  run-quanlity-code:
    runs-on: ubuntu-latest # Runner free 
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Using docker to check convention code 
        run: |
          echo "Start lint..." 
          echo "Install tool..." #Install tool if github action is not built-in 
          npm install globals
          npm install -g eslint 
          eslint *.js --fix
          echo "Lint done."
