name: Hello workflows
on:
  push: 
    branches:
      - feat/ci-cd 
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Step setup node version 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Step check node version
        run: node -v